name: Python CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List files in root
      run: ls -l

    - name: List files in python3-app
      working-directory: python3-app
      run: ls -l

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      working-directory: python3-app
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run app server
      working-directory: python3-app
      run: |
        nohup python3 main.py &
        sleep 5

    - name: Run tests
      working-directory: python3-app
      run: |
        set -x  # включить подробный вывод команд
        python --version
        pip --version
        echo "Запускаем тесты..."
        python -m unittest discover tests -v || (echo "Тесты завершились с ошибкой"; exit 1)

